### ISSUE TITLE
Initial config

### ISSUE THREAD

**Issue by ppalella** [arturf/yii2-auth#3]
I can not access the url of the system administrator, when trying to access, it displays the error message: "Class auth\Module does not exist" to get [home_url]/auth
Can you help me set up correctly?

```
File: module.php
    'auth' => [
        'class' => 'auth\Module',
    ],

File: web.php
    'components' => [
        'authManager' => [
            'class' => 'auth\components\DbManager',
        ],
```

**Comment by arturf** [comment]
Can you show stack trace?

**Comment by ppalella** [comment]
1. in ...\vendor\yiisoft\yii2\di\Container.php at line 415
   406407408409410411412413414415416417418419420421422423424     \* @return array the dependencies of the specified class.
    */
   protected function getDependencies($class)
   {
       if (isset($this->_reflections[$class])) {
           return [$this->_reflections[$class], $this->_dependencies[$class]];
       }
   
   ```
   $dependencies = [];
   $reflection = new ReflectionClass($class);
   
   $constructor = $reflection->getConstructor();
   if ($constructor !== null) {
       foreach ($constructor->getParameters() as $param) {
           if ($param->isDefaultValueAvailable()) {
               $dependencies[] = $param->getDefaultValue();
           } else {
               $c = $param->getClass();
               $dependencies[] = Instance::of($c === null ? null : $c->getName());
   ```
2. in ...\vendor\yiisoft\yii2\di\Container.php at line 415 – ReflectionClass::__construct('binn\yii2-auth\Module')
3. in ...\vendor\yiisoft\yii2\di\Container.php at line 358 – yii\di\Container::getDependencies('binn\yii2-auth\Module')
4. in ...\vendor\yiisoft\yii2\di\Container.php at line 151 – yii\di\Container::build('binn\yii2-auth\Module', ['auth', yii\web\Application], [])
5. in ...\vendor\yiisoft\yii2\BaseYii.php at line 344 – yii\di\Container::get('binn\yii2-auth\Module', ['auth', yii\web\Application], [])
6. in ...\vendor\yiisoft\yii2\base\Module.php at line 354 – yii\BaseYii::createObject(['class' => 'binn\yii2-auth\Module'], ['auth', yii\web\Application])
7. in ...\vendor\yiisoft\yii2\base\Module.php at line 511 – yii\base\Module::getModule('auth')
8. in ...\vendor\yiisoft\yii2\base\Module.php at line 449 – yii\base\Module::createController('auth/assignment/options')
9. in ...\vendor\yiisoft\yii2\web\Application.php at line 84 – yii\base\Module::runAction('auth/assignment/options', [])
10. in ...\vendor\yiisoft\yii2\base\Application.php at line 375 – yii\web\Application::handleRequest(yii\web\Request)
11. in ...\web\index.php at line 12 – yii\base\Application::run()
    6789101112 
    require(**DIR** . '/../vendor/autoload.php');
    require(**DIR** . '/../vendor/yiisoft/yii2/Yii.php');

$config = require(**DIR** . '/../config/web.php');

(new yii\web\Application($config))->run();

**Comment by ppalella** [comment]
Any ideas or suggestions?

**Comment by arturf** [comment]
Sorry for delay. Seems this is autoload problem, di search classes in incorrect place:  
`yii\di\Container::getDependencies('binn\yii2-auth\Module')`  
`yii\di\Container::get('binn\yii2-auth\Module'`  

Did you install package via composer?..

Also you can try to add alias manually - `Yii::setAlias('auth', Yii::getAlias('@vendor/binn/yii2-auth'));`

**Comment by arturf** [comment]
I'll close this..
